apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
  namespace: githubissues-operator-system
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: SECRET_Token
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: token
