---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-training-redhat-com-v1alpha1-githubissue
  failurePolicy: Fail
  name: vgithubissue.kb.io
  rules:
  - apiGroups:
    - training.redhat.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubissues
  sideEffects: None
